HotelOrderFinal/Models/Discount.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelOrderFinal.Models
{
    public partial class Discount
    {
        public Discount()
        {
            DiscountDetail = new HashSet<DiscountDetail>();
            Order = new HashSet<Order>();
        }

        public int DiscountId { get; set; }
        public string DiscountName { get; set; }
        public string DiscountImage { get; set; }
        public string DiscountDirections { get; set; }
        public decimal? DiscountDiscount { get; set; }
        public bool? DiscountExist { get; set; }

        public virtual ICollection<DiscountDetail> DiscountDetail { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}

HotelOrderFinal/Controllers/DiscountController.cs
using HotelOrderFinal.Models;
using HotelOrderFinal.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace HotelOrderFinal.Controllers
{
    public class DiscountController : Controller
    {
        private HotelOrderContext db = new HotelOrderContext();
        public IHttpContextAccessor _contextAccessor;
        public IWebHostEnvironment _enviro;

        public DiscountController(IHttpContextAccessor contextAccessor , IWebHostEnvironment enviro)
        {
            this._contextAccessor = contextAccessor;
            _enviro = enviro;
            
        }

        public IActionResult List(CKeywordViewModel vm)
        {
            IEnumerable<Discount> datas = null;
            if (string.IsNullOrEmpty(vm.txtKeyword))
                datas = from c in db.Discount
                        select c;
            else
                return RedirectToAction("Index", "Home");
            return View(datas);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Discount p, CDiscountWrap x)
        {
            try
            {
                // 取得優惠是否存在
                p.DiscountExist = true;
                db.Discount.Add(p);
                db.SaveChanges();

                // 取得當時的會員數量
                int memberCount = db.RoomMember.Count();
                Discount cust = db.Discount.FirstOrDefault(t => t.DiscountId == p.DiscountId);

                if (cust != null)
                {
                    if (x.photo != null)
                    {
                        string photoName = Guid.NewGuid().ToString() + ".jpg";
                        string path = _enviro.WebRootPath + "/image/" + photoName;
                        using (var stream = new FileStream(path, FileMode.Create))
                        {
                            x.photo.CopyTo(stream);
                        }
                        cust.DiscountImage = photoName;
                    }

                    cust.DiscountName = x.DiscountName;
                    cust.DiscountDirections = x.DiscountDirections;
                    cust.DiscountDiscount = x.DiscountDiscount;
                    cust.DiscountExist = x.DiscountExist;
                    db.SaveChanges();
                }

                if (memberCount > 0)
                {
                    // 所有的會員ID
                    var members = db.RoomMember.Select(x => x.MemberId);

                    int lastID = db.Discount.OrderByDescending(x => x.DiscountId).FirstOrDefault().DiscountId;

                    foreach (var itme in members)
                    {
                        DiscountDetail detail = new DiscountDetail();
                        detail.DiscountId = lastID;
                        detail.DiscountStart = DateTime.Now;
                        detail.DiscountEnd = DateTime.Now.AddMonths(3);
                        detail.DiscountUse = 0;
                        detail.MemberId = itme;
                        db.DiscountDetail.Add(detail);
                    }

                    db.SaveChanges();
                }

                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                return View();
            }
        }

        //public IActionResult Create(Discount p , CDiscountWrap x)
        //{
        //    try
        //    {
        //        // 取得優惠是否存在
        //        p.DiscountExist = true;
        //        db.Discount.Add(p);
        //        db.SaveChanges();


        //        // 取得當時的會員數量
        //        int memberCount = db.RoomMember.Count();
        //        Discount cust = db.Discount.FirstOrDefault(t => t.DiscountId == p.DiscountId);
        //        if (cust != null)
        //        {
        //            if (x.photo != null)
        //            {
        //                string photoName = Guid.NewGuid().ToString() + ".jpg";
        //                string path = _enviro.WebRootPath + "/image/" + photoName;
        //                x.photo.CopyTo(new FileStream(path, FileMode.Create));
        //                cust.DiscountImage = photoName;
        //            }

        //            cust.DiscountName = x.DiscountName;
        //            cust.DiscountDirections = x.DiscountDirections;
        //            cust.DiscountDiscount = x.DiscountDiscount;
        //            cust.DiscountExist = x.DiscountExist;
        //            db.SaveChanges();
        //        }
        //        if (p.DiscountExist == true && memberCount > 0)
        //        {
        //            //所有的會員ID
        //            var members = db.RoomMember.Select(x => x.MemberId);

        //            int lastID = db.Discount.OrderByDescending(x => x.DiscountId).FirstOrDefault().DiscountId;
        //            foreach (var itme in members)
        //            {
        //                DiscountDetail detail = new DiscountDetail();
        //                detail.DiscountId = lastID;
        //                detail.DiscountStart = DateTime.Now;
        //                detail.DiscountEnd = DateTime.Now.AddMonths(3);
        //                detail.DiscountUse = 0;
        //                detail.MemberId = itme;
        //                db.DiscountDetail.Add(detail);
        //            }
        //            db.SaveChanges();
        //            return RedirectToAction("List");
        //        }                
        //        return RedirectToAction("List");
        //    }
        //    catch (Exception ex)
        //    {
        //        Console.WriteLine(ex.ToString());
        //        return View();
        //    }
        //}

        public IActionResult Delete(int? id)
        {
            
            Discount cust = db.Discount.FirstOrDefault(t => t.DiscountId == id);
            if (cust != null)
            {
                db.Discount.Remove(cust);
                db.SaveChanges();
            }
            return RedirectToAction("List");
        }
        public IActionResult Edit(int? id)
        {           
            Discount cust = db.Discount.FirstOrDefault(t => t.DiscountId == id);
            if (cust == null)
                return RedirectToAction("List");
            return View(cust);
        }
        [HttpPost]
        public IActionResult Edit(CDiscountWrap p)
        {

            Discount cust = db.Discount.FirstOrDefault(t => t.DiscountId == p.DiscountId);
            if (cust != null)
            {
                if (p.photo != null)
                {
                    string photoName = Guid.NewGuid().ToString() + ".jpg";
                    string path = _enviro.WebRootPath + "/image/" + photoName;
                    p.photo.CopyTo(new FileStream(path, FileMode.Create));
                    cust.DiscountImage = photoName;
                }

                cust.DiscountName = p.DiscountName;
                cust.DiscountDirections = p.DiscountDirections;
                cust.DiscountDiscount = p.DiscountDiscount;
                cust.DiscountExist = p.DiscountExist;           
                db.SaveChanges();
            }
            return RedirectToAction("List");
        }
        //public IActionResult Edit(Discount p)
        //{           
        //    Discount cust = db.Discount.FirstOrDefault(t => t.DiscountId == p.DiscountId);
        //    if (cust != null)
        //    {
        //        cust.DiscountName = p.DiscountName;
        //        cust.DiscountImage = p.DiscountImage;
        //        cust.DiscountDirections = p.DiscountDirections;
        //        cust.DiscountDiscount = p.DiscountDiscount;
        //        db.SaveChanges();
        //    }
        //    return RedirectToAction("List");
        //}

        public IActionResult DiscountByMember()
        {
            var userId = _contextAccessor.HttpContext.Session.GetString("UserID");

            //IEnumerable<DiscountDetail> usesid = db.DiscountDetail.Where(x => x.MemberId == userId);
            //var 這個會員的優惠=db.DiscountDetail.Where(d => d.MemberId == userId);
            //List<string> discountNames = new List<string>();
            //foreach(var item in 這個會員的優惠)
            //{
            //    var 優惠類型=db.Discount.FirstOrDefault(d=>d.DiscountId==(int)item.DiscountId);
            //    if (優惠類型 != null)
            //        discountNames.Add(優惠類型.DiscountName);
            //}
            //CTingViewModel vm = new CTingViewModel();
            //vm.names = discountNames;
            //vm.xx = usesid;

            List<CDiscountViewModel> list = new List<CDiscountViewModel>();
            var discountDetails=db.DiscountDetail.Where(x => x.MemberId == userId).ToList();
            foreach(var item in discountDetails)
            {
                CDiscountViewModel vm = new CDiscountViewModel();
                vm.discountDetail = item;
                var 取得優惠資料=db.Discount.FirstOrDefault(x => x.DiscountId == item.DiscountId);
                vm.names = 取得優惠資料.DiscountName;
                list.Add(vm);
            }
            //IEnumerable<Discount> usesid = db.Discount.Where(x => x.MemberId == userId);
            //return View(usesid);
            return View(list);
        }
    }
}

HotelOrderFinal/Views/Discount/Create.cshtml
@model HotelOrderFinal.Models.Discount

@{
    ViewData["Title"] = "Create";
}

<section class="breadcrumb_area">
    <div class="overlay bg-parallax" data-stellar-ratio="0.8" data-stellar-vertical-offset="0" data-background=""></div>
    <div class="container">
        @*  <div class="page-cover text-center">
        <h2 class="page-cover-tittle">About Us</h2>
        <ol class="breadcrumb">
        <li><a href="index.html">Home</a></li>
        <li class="active">About</li>
        </ol>
        </div>*@
    </div>
</section>

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @*    <title>評點&評論</title>*@
    <link rel="stylesheet" href="../css/start.css" />
    <style>
        .card-text {
            display: -webkit-box;
            -webkit-box-orient: vertical;
            -webkit-line-clamp: 2;
            line-clamp: 2;
            overflow: hidden;
        }

        * {
            margin: 0;
            padding: 0;
        }

        /* .類別名 可套用在不同標籤上*/
        .left {
            width: 400px;
            float: left;
            margin-left: 100px;
        }

        .t1 {
            /* float: left; 文繞圖浮動到左邊*/
            float: left;
        }

        .t2 {
            width: 400px;
            text-align: center;
        }

        .sub {
            width: 400px;
            /* 捲軸:視需要自動啟動 */
            overflow: auto;
            margin-left: 10px;
            text-align: start;
        }
        /* 不能任意調整文字框大小 */
        textarea {
            margin-left: 10px;
            resize: none;
        }
    </style>
</head>

<body>

    <div class="container-fluid">
           <div class="row">
    <div class="col-md-6 offset-md-3">
                    <div class="d-flex flex-wrap">
                        @*    <div class="col-md-4">*@
                        <form asp-action="Create" enctype="multipart/form-data">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                            @*<label asp-for="DiscountId" class="control-label"></label>*@
                            <input type="hidden" asp-for="DiscountId" class="form-control" />
                            <span asp-validation-for="DiscountId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="DiscountName" class="control-label">優惠名稱</label>
                                <input  asp-for="DiscountName" class="form-control" />
                                <span asp-validation-for="DiscountName" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="DiscountImage" class="control-label">優惠圖片</label>
                                <input asp-for="DiscountImage" class="form-control" />
                                <span asp-validation-for="DiscountImage" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="DiscountDirections" class="control-label">優惠詳細</label>
                                <input asp-for="DiscountDirections" class="form-control" />
                                <span asp-validation-for="DiscountDirections" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="DiscountDiscount" class="control-label">優惠折扣</label>
                                <input asp-for="DiscountDiscount" class="form-control" />
                                <span asp-validation-for="DiscountDiscount" class="text-danger"></span>
                            </div>
                                    <div class="form-group">
                                    <label class="control-label">優惠照片</label>
                                    <input type="file" name="photo" class="form-control" />
                            </div>

                            @*<div class="form-group">
                            <label asp-for="MemberId" class="control-label"></label>
                            <input asp-for="MemberId" class="form-control" />
                            <span asp-validation-for="MemberId" class="text-danger"></span>
                            </div>*@
                            <div class="form-group">
                            <input type="submit" value="新增優惠" class="btn btn-primary" />
                                <input type="reset" value="清除" class="btn btn-secondary" />
                            <a asp-action="List" class="btn btn-warning">取消</a>
                            </div>
                            <div class="form-group">
                                @using (Html.BeginForm("Create", "Discount", new { id = "my-form-id" }))
                                {
                                    <button type="button" class="btn btn-secondary" onclick="demoDiscount()">Demo</button>
                                }
                                @ViewBag.Message
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    
</body>




@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
   
    <script>
        function demoDiscount() {
            // 設定 Demo 評價
            // 取得表單元素和欄位元素
            document.getElementById("DiscountName").value = "促進經濟旅遊";
            document.getElementById("DiscountDirections").value = "就是來住宿";
            document.getElementById("DiscountDiscount").value = 0.8;           
            //// 提交表單
            form.submit();
        }
    </script>
    }
}

HotelOrderFinal/Views/Discount/DiscountByMember.cshtml
@*@model IEnumerable<HotelOrderFinal.Models.DiscountDetail>*@
    @model List< HotelOrderFinal.ViewModels.CDiscountViewModel>

@{
    ViewData["Title"] = "List";
}

<section class="breadcrumb_area">
    <div class="overlay bg-parallax" data-stellar-ratio="0.8" data-stellar-vertical-offset="0" data-background=""></div>
    <div class="container">
        @*  <div class="page-cover text-center">
        <h2 class="page-cover-tittle">About Us</h2>
        <ol class="breadcrumb">
        <li><a href="index.html">Home</a></li>
        <li class="active">About</li>
        </ol>
        </div>*@
    </div>
</section>
<style>
    .wrapper {
        width: 80%; /* 設定容器寬度 */
        margin: 0 auto; /* 將容器置中對齊 */
    }

    table th {
        white-space: nowrap;
    }
</style>
<div class="wrapper ">

    <h1>會員優惠折扣</h1>
    <hr />
    <div class="row">
        @*//【側邊欄位】==========================================================================*@
        <div class="col-xs-12 col-md-3">
            <div class="athMember__menu pb-sm-3">
                <div class="athMember__user pb-20">
                    <div class="athMember__userInfo">
                        @{
                            var userName = Context.Session.GetString("UserName");
                            var userId = Context.Session.GetString("UserID");
                            var usePhone = Context.Session.GetString("UserPhone");
                        }
                        <h2 class="athMember__userName">@userName</h2>
                        @*<p class="athMember__usePhone">@usePhone</p>*@
                    </div>
                </div>
                <div class="athMemberNav">
                    <ul class="athMember__menuList d-mdx-none pb-15 mt-10" style="list-style: none;">
                        <li class="athMember__menu__isactive">
                            @Html.ActionLink("修改資料", "Edit", "Member", null, new { @class = "nav-link Adminbutton  d-flex justify-content-center" })
                        </li>
                        <li class="athMember__menu__isactive">
                            @Html.ActionLink("修改密碼", "EditPassword", "Member", null, new { @class = "nav-link Adminbutton  d-flex justify-content-center" })
                        </li>
                        <li class="athMember__menu__isactive">
                            @Html.ActionLink("您的訂單", "ShoppingCar", "Member", null, new { @class = "nav-link Adminbutton  d-flex justify-content-center" })
                        </li>
                        <li class="athMember__menu__isactive">
                            @Html.ActionLink("優惠折扣", "DiscountByMember", "Discount", null, new { @class = "nav-link Adminbutton  d-flex justify-content-center" })
                        </li>
                        <li class="athMember__menu__isactive">
                            @Html.ActionLink("您的評論", "ListByMember", "Comment", null, new { @class = "nav-link Adminbutton  d-flex justify-content-center" })
                        </li>
                        @*<li class="athMember__menu__isactive" hidden>*@
                        @*@Html.ActionLink("最新消息", "News", "Member", null, new { @class = "nav-link Adminbutton  d-flex justify-content-center" })*@
                        @*</li>*@
                        <li class="athMember__menu__isactive">
                            @Html.ActionLink("會員條款", "terms", "Member", null, new { @class = "nav-link Adminbutton  d-flex justify-content-center" })
                        </li>
                        @*<li class="athMember__menu__isactive" hidden>*@
                        @*@Html.ActionLink("電子會員卡", "MemberCard", "Member", null, new { @class = "nav-link Adminbutton  d-flex justify-content-center" })*@
                        @*</li>*@

                    </ul>
                    <div class="d-md-none">
                        <p class="athMember__menu__select mt-20 mb-10">會員資料選單</p>
                        <div class="athMember__menuList form-group athSelect w-100">
                            <select class="form-control">
                                <option value="memberEdit">修改資料</option>
                                <option value="passwordEdit">修改密碼</option>
                                <option value="getOrderQueryMn">您的訂單</option>
                                <option value="getNews">最新消息</option>
                                <option value="memberRule">會員條款</option>
                                <option value="memberBenefit">會員福利</option> <!----> <!---->
                                <option value="memberCard">電子會員卡</option> <!----> <!---->
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        @*///-----------------------------------------------------------------------------------------*@

        <div class="col-xs-12 col-md-3">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            編號
                        </th>
                        @*<th>
                        @Html.DisplayNameFor(model => model.DiscountId)
                        </th>*@
                        <th>
                            優惠名稱
                        </th>
                        <th>
                            優惠開始時間
                            @*@Html.DisplayNameFor(model => model.DiscountStart)*@
                        </th>
                        <th>
                            優惠結束時間
                            @*@Html.DisplayNameFor(model => model.DiscountEnd)*@
                        </th>
                        <th>
                            優惠是否使用
                            @*@Html.DisplayNameFor(model => model.DiscountUse)*@
                        </th>
                        @*@<th>
                        @Html.DisplayNameFor(model => model.MemberId)
                        </th>*@

                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        int count = 0;
                        @foreach (var item in Model)
                        {
                            count++;
                            <tr>
                                <td>
                                    @count
                                </td>
                                <td style="white-space: nowrap;">
                                    @item.names
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.discountDetail.DiscountStart)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.discountDetail.DiscountEnd)
                                </td>
                                <td>
                                    @*@Html.DisplayFor(modelItem => item.DiscountUse)*@
                                    @{
                                        string s1 = "";
                                        if (item.discountDetail.DiscountUse == 0)
                                        { s1 = "可使用"; }
                                        else if (item.discountDetail.DiscountUse == 1)
                                        { s1 = "已使用"; }
                                    }
                                    @Html.Raw(s1)
                                </td>
                                @*<td>
                        @Html.DisplayFor(modelItem => item.MemberId)
                        </td>*@

                                @*<td>
                        @Html.ActionLink("修改", "Edit", new {  id=item.DiscountId  }) |
                        @Html.ActionLink("刪除", "Delete","Discount", new {  id=item.DiscountId },new {onclick="return confirm('確定刪除嗎?')"})
                        </td>*@
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

HotelOrderFinal/Views/Discount/List.cshtml
@model IEnumerable<HotelOrderFinal.Models.Discount>

@{
    ViewData["Title"] = "List";
}
<link rel="stylesheet" href="~/css/ForAdminTable.css">
<section class="breadcrumb_area">
    <div class="overlay bg-parallax" data-stellar-ratio="0.8" data-stellar-vertical-offset="0" data-background=""></div>
    <div class="container">
        <div class="page-cover text-center">
            <h2 class="page-cover-tittle">後台管理系統：優惠管理</h2>
        </div>
    </div>
</section>
@*<h1>優惠管理</h1>*@
<div class="Adminwrapper">
    <div class="row">
        <div class="col-xs-12 col-md-2">
            <div class=" ">
                <div class=" ">
                    <div class="">
                        @{
                            var AdminId = Context.Session.GetString("AdminId");
                        }

                    </div>
                </div>
                <div class="">
                    <h2 style="text-align: center">
                        @Html.ActionLink(AdminId, "List", "Admin")
                    </h2>
                    <ul class="list" style="list-style: none; padding: 0;">

                        <!--改成手風琴下拉式-->
                        <li>
                            @Html.ActionLink("會員管理", "List", "MemberMange", null, new { @class = "nav-link Adminbutton  d-flex justify-content-center" })
                        </li>
                        <li>
                            @Html.ActionLink("房型管理", "AdminRoom", "Room", null, new { @class = "nav-link Adminbutton  d-flex justify-content-center" })
                        </li>
                        <li>
                            @Html.ActionLink("活動管理", "ActivityByCreate", "Activity", null, new { @class = "nav-link Adminbutton  d-flex justify-content-center" })
                        </li>
                        <li>
                            @Html.ActionLink("訂房管理", "EditPassword", "Member", null, new { @class = "nav-link Adminbutton  d-flex justify-content-center" })
                        </li>
                        <li>
                            @Html.ActionLink("飯店一覽管理", "ListView", "HotelIndustry", null, new { @class = "nav-link Adminbutton  d-flex justify-content-center" })
                        </li>
                        <li>
                            @Html.ActionLink("優惠折扣管理", "List", "Discount", null, new { @class = "nav-link Adminbutton  d-flex justify-content-center" })
                        </li>
                        <li>
                            @Html.ActionLink("評論管理", "ListByAdmin", "Comment", null, new { @class = "nav-link Adminbutton  d-flex justify-content-center" })
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div id="selectedItemContent" class="col-xs-12 col-md-10 ">
            <!-- 這裡會顯示點選的項目的內容 -->
<table class="table">
    <thead>
        <tr>
            <th>
                編號
                @*@Html.DisplayNameFor(model => model.DiscountId)*@
            </th>
            <th>
                優惠名稱
                @*@Html.DisplayNameFor(model => model.DiscountName)*@
            </th>
            <th>
                優惠照片
                @*@Html.DisplayNameFor(model => model.DiscountImage)*@
            </th>
            <th>
                優惠詳細
                @*@Html.DisplayNameFor(model => model.DiscountDirections)*@
            </th>
            
            <th>
                優惠折數
                @*@Html.DisplayNameFor(model => model.DiscountDiscount)*@
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.MemberId)
            </th>*@
            <th>
                <a asp-action="Create" class="btn btn-info">新增優惠</a>
            </th>
        </tr>
    </thead>
    <tbody>
        @{
            int count = 0;
@foreach (var item in Model) {            
            count++;
            <tr>
            <td>
                @count
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiscountName)
            </td>
            <td>
                 <img src="~/image/@item.DiscountImage" width="160" height="120" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiscountDirections)
            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.DiscountDiscount)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.MemberId)
            </td>*@

                <td>
                    @Html.ActionLink("修改", "Edit", new {id=item.DiscountId},new { @class="btn btn-success" }) 
                    @Html.ActionLink("刪除", "Delete","Discount", new {  id=item.DiscountId },new { @class="btn btn-danger", onclick="return confirm('確定要刪除嗎?')"})
                </td>
        </tr>
}
        }
    </tbody>
</table>
</div>
</div>
</div>