HotelOrderFinal/Models/Comment.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace HotelOrderFinal.Models
{
    public partial class Comment
    {
        public int CommentId { get; set; }
        [DisplayName("評點日期")]
        public DateTime? CommentDate { get; set; }
        [DisplayName("會員編號")]
        public string MemberId { get; set; }
        [DisplayName("分　類")]
        public int? CommentClass { get; set; }
        [DisplayName("評　　　　　　　點")]
        public int? CommentPoint { get; set; }
        [DisplayName("評論摘要")]
        public string CommentDetail { get; set; }

        public virtual RoomMember Member { get; set; }
    }
}

HotelOrderFinal/Controllers/CommentController.cs
using HotelOrderFinal.Models;
using HotelOrderFinal.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata;
using System.Linq;

namespace HotelOrderFinal.Controllers
{
    public class CommentController : Controller
    {
        public IHttpContextAccessor _contextAccessor;
        public CommentController(IHttpContextAccessor contextAccessor)
        {
            this._contextAccessor = contextAccessor;
        }
        public IActionResult List(CKeywordViewModel vm)
        {
            HotelOrderContext db = new HotelOrderContext();
            IEnumerable<Comment> datas = null;
            if (string.IsNullOrEmpty(vm.txtKeyword))
                datas = from c in db.Comment
                        orderby c.CommentDate descending
                        select c;
            else
                datas = db.Comment
                    .Where(p => p.CommentDetail.Contains(vm.txtKeyword))
                    .OrderByDescending(p => p.CommentDate);
            return View(datas);
        }
        public IActionResult ListByMember(string? UserID)
        {
            var userId = _contextAccessor.HttpContext.Session.GetString("UserID");
            HotelOrderContext db = new HotelOrderContext();
            IEnumerable<Comment> member = db.Comment
                                          .Where(t => t.MemberId == userId)
                                          .OrderByDescending(p => p.CommentDate);
            if (member == null)
                return RedirectToAction("ListByMemberAll");
            return View(member);
        }

        public IActionResult ListByMemberAll(CKeywordViewModel vm)
        {
            HotelOrderContext db = new HotelOrderContext();
            IEnumerable<Comment> datas = null;
            if (string.IsNullOrEmpty(vm.txtKeyword))
                datas = from c in db.Comment
                        orderby c.CommentDate descending
                        select c;
            else
                datas = db.Comment
                    .Where(p => p.CommentDetail.Contains(vm.txtKeyword))
                    .OrderByDescending(p => p.CommentDate);
            return View(datas);
        }
        public IActionResult ListByAdmin(CKeywordViewModel vm)
        {
            HotelOrderContext db = new HotelOrderContext();
            IEnumerable<Comment> datas = null;
            if (string.IsNullOrEmpty(vm.txtKeyword))
                datas = from c in db.Comment
                        orderby c.CommentDate descending
                        select c;
            else
                datas = db.Comment
                    .Where(p => p.CommentDetail.Contains(vm.txtKeyword))
                    .OrderByDescending(p => p.CommentDate);
            return View(datas);
        }
        public IActionResult Create(string? UserID)
        {
            var userId = _contextAccessor.HttpContext.Session.GetString("UserID");
            ViewBag.UserID = userId;
            return View();
        }
        [HttpPost]
        public IActionResult Create(Comment p)
        {
            HotelOrderContext db = new HotelOrderContext();
            db.Comment.Add(p);
            db.SaveChanges();
            return RedirectToAction("ListByMember");
        }
        public IActionResult CreateByAdmin()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateByAdmin(Comment p)
        {
            HotelOrderContext db = new HotelOrderContext();
            db.Comment.Add(p);
            db.SaveChanges();
            return RedirectToAction("ListByAdmin");
        }
        public IActionResult Edit(int? id)
        {
            HotelOrderContext db = new HotelOrderContext();
            Comment comment = db.Comment.FirstOrDefault(t => t.CommentId == id);
            if (comment == null)
                return RedirectToAction("ListByMember");
            return View(comment);
        }
        [HttpPost]
        public IActionResult Edit(Comment p)
        {
            HotelOrderContext db = new HotelOrderContext();
            Comment comment = db.Comment.FirstOrDefault(t => t.CommentId == p.CommentId);
            if (comment != null)
            {
                comment.CommentDetail = p.CommentDetail;
                db.SaveChanges();
            }
            return RedirectToAction("ListByMember");
        }
        public IActionResult EditByAdmin(int? id)
        {
            HotelOrderContext db = new HotelOrderContext();
            Comment commentA = db.Comment.FirstOrDefault(t => t.CommentId == id);
            if (commentA == null)
                return RedirectToAction("ListByAdmin");
            return View(commentA);
        }
        [HttpPost]
        public IActionResult EditByAdmin(Comment p)
        {
            HotelOrderContext db = new HotelOrderContext();
            Comment commentA = db.Comment.FirstOrDefault(t => t.CommentId == p.CommentId);
            if (commentA != null)
            {
                commentA.CommentDetail = p.CommentDetail;
                db.SaveChanges();
            }
            return RedirectToAction("ListByAdmin");
        }
        public IActionResult Delete(int? id)
        {
            HotelOrderContext db = new HotelOrderContext();
            Comment comment = db.Comment.FirstOrDefault(t => t.CommentId == id);
            if (comment != null)
            {
                db.Comment.Remove(comment);
                db.SaveChanges();
            }
            return RedirectToAction("ListByMember");
        }
        public IActionResult DeleteByAdmin(int? id)
        {
            HotelOrderContext db = new HotelOrderContext();
            Comment comment = db.Comment.FirstOrDefault(t => t.CommentId == id);
            if (comment != null)
            {
                db.Comment.Remove(comment);
                db.SaveChanges();
            }
            return RedirectToAction("ListByAdmin");
        }
    }
}

HotelOrderFinal/Views/Comment/Create.cshtml
@model HotelOrderFinal.Models.Comment

@{
    ViewData["Title"] = "Create";
}

<section class="breadcrumb_area">
    <div class="overlay bg-parallax" data-stellar-ratio="0.8" data-stellar-vertical-offset="0" data-background=""></div>
    <div class="container">
        <div class="page-cover text-center">
            <h2 class="page-cover-tittle">會員管理系統:你的評論</h2>
        </div>
    </div>
</section>
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @*    <title>評點&評論</title>*@
    <link rel="stylesheet" href="../css/start.css" />
    <style>
        .card-text {
            display: -webkit-box;
            -webkit-box-orient: vertical;
            -webkit-line-clamp: 2;
            line-clamp: 2;
            overflow: hidden;
        }

        * {
            margin: 0;
            padding: 0;
        }

        /* .類別名 可套用在不同標籤上*/
        .left {
            width: 400px;
            float: left;
            margin-left: 100px;
        }

        .t1 {
            /* float: left; 文繞圖浮動到左邊*/
            float: left;
        }

        .t2 {
            width: 400px;
            text-align: center;
        }

        .sub {
            width: 400px;
            /* 捲軸:視需要自動啟動 */
            overflow: auto;
            margin-left: 10px;
            text-align: start;
        }
        /* 不能任意調整文字框大小 */
        textarea {
            margin-left: 10px;
            resize: none;
        }
    </style>
</head>
<body>
    <div class="container-fluid">
        <div class="row" style="background-color: #dcebfd;">
            <div class="col-md-2"></div>
            <p></p>
            <h4>新增評論</h4>
            <hr />

            @*            <div class="row">
            <div class="col-5 col-1-sm-6">*@
            <div class="row">
                <div class="col-md-4">
                    <div class="d-flex flex-wrap">

                        <form asp-action="Create">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                            <div class="form-group">
                                <input type="hidden" asp-for="CommentDate" value=getdate() />
                                <span asp-validation-for="CommentDate" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <input type="hidden" asp-for="MemberId" value="@ViewBag.UserID" />
                                <span asp-validation-for="MemberId" class="text-danger"></span>
                            </div>
                            <br>
                            <div class="form-group" style="padding-left:5px;font-size: 17px; color:#000000">
                                <label>評價分類：</label>
                                <label class="lab1">
                                    <input sp-for="CommentClass" type="radio" name="CommentClass" value="1" required checked />整體
                                </label>
                                <label class="lab1">
                                    <input sp-for="CommentClass" type="radio" name="CommentClass" value="2" />房間
                                </label>
                                <label class="lab1">
                                    <input sp-for="CommentClass" type="radio" name="CommentClass" value="3" />服務
                                </label>
                            </div>

                            <label>請給予評點:</label>
                            <div id="stars" class="left">
                                <img src="../image/comment/empty.png" title="非常失望" alt="">
                                <img src="../image/comment/empty.png" title="不滿意" alt="">
                                <img src="../image/comment/empty.png" title="普通" alt="">
                                <img src="../image/comment/empty.png" title="滿意" alt="">
                                <img src="../image/comment/empty.png" title="非常滿意" alt="">
                                <span id="score"></span>
                            </div>

                            <p></p>
                            <input type="hidden" asp-for="CommentPoint" value="-1" />
                            <span asp-validation-for="CommentPoint"></span>
                            <br>
                            <div class="sub">
                                <label asp-for="CommentDetail" class="control-label"></label>
                                <textarea asp-for="CommentDetail" cols="40" rows="5" autofocus placeholder="請讓我們了解您的感受...."></textarea>
                                <span asp-validation-for="CommentDetail" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <input type="submit" value="儲存" class="btn btn-primary" />
                                <input type="reset" value="清除" class="btn btn-secondary" />
                                <a asp-action="ListByMember" class="btn btn-warning">取消</a>
                            </div>
                            <div class="form-group">
                                @using (Html.BeginForm("Create", "Comment", new { id = "my-form-id" }))
                                {
                                    <button type="button" class="btn btn-secondary" onclick="demoComment()">Demo</button>
                                }
                                @ViewBag.Message
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
</body>
@section Scripts
    {
    <script src="~/js/comment/commentpoint.js"></script>

    <script type="text/javascript">
        function demoComment() {
            // 取得表單元素和欄位元素
            var CommentDetail = document.getElementById("CommentDetail");
            // 設定 Demo 評價
            CommentDetail.value = "很舒適的住房體驗，浴室乾濕分離，獨立浴缸不會有邊角發霉問題，整體乾淨整潔。";
            // 提交表單
            form.submit();
        }
    </script>
}

HotelOrderFinal/Views/Comment/CreateByAdmin.cshtml
@model HotelOrderFinal.Models.Comment

@{
    ViewData["Title"] = "CreateByAdmin";
}

<section class="breadcrumb_area">
    <div class="overlay bg-parallax" data-stellar-ratio="0.8" data-stellar-vertical-offset="0" data-background=""></div>
    <div class="container">
        <div class="page-cover text-center">
            <h2 class="page-cover-tittle">後台管理系統:評論管理</h2>
        </div>
    </div>
</section>
<p></p>
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @*    <title>評點&評論</title>*@
    <link rel="stylesheet" href="../css/start.css" />
    <style>
        .card-text {
            display: -webkit-box;
            -webkit-box-orient: vertical;
            -webkit-line-clamp: 2;
            line-clamp: 2;
            overflow: hidden;
        }

        * {
            margin: 0;
            padding: 0;
        }

        /* .類別名 可套用在不同標籤上*/
        .left {
            width: 400px;
            float: left;
            margin-left: 100px;
        }

        .t1 {
            /* float: left; 文繞圖浮動到左邊*/
            float: left;
        }

        .t2 {
            width: 400px;
            text-align: center;
        }

        .sub {
            width: 400px;
            /* 捲軸:視需要自動啟動 */
            overflow: auto;
            margin-left: 10px;
            text-align: start;
        }
        /* 不能任意調整文字框大小 */
        textarea {
            margin-left: 10px;
            resize: none;
        }
    </style>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2" style="background-color: #f2f2f2;">
            </div>
            <div class="col-md-10">
                <p></p>
                <h4>新增評論</h4>
                <hr />

                <div class="row">
                    <div class="col-md-4" style="font-size: 17px">

                        <form asp-action="CreateByAdmin">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <input type="hidden" asp-for="CommentDate" value=getdate() />
                                <span asp-validation-for="CommentDate" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="MemberId" class="control-label"></label>
                                <input asp-for="MemberId" class="form-control" />
                                <span asp-validation-for="MemberId" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label>評價分類：</label>
                                <label class="lab1">
                                    <input sp-for="CommentClass" type="radio" name="CommentClass" value="1" required checked />整體
                                </label>
                                <label class="lab1">
                                    <input sp-for="CommentClass" type="radio" name="CommentClass" value="2"/>房間
                                </label>
                                <label class="lab1">
                                    <input sp-for="CommentClass" type="radio" name="CommentClass" value="3" />服務
                                </label>
                            </div>
                            <label>請給予評點:</label>
                            <div id="stars" class="left">
                                <img src="../image/comment/empty.png" title="非常失望" alt="">
                                <img src="../image/comment/empty.png" title="不滿意" alt="">
                                <img src="../image/comment/empty.png" title="普通" alt="">
                                <img src="../image/comment/empty.png" title="滿意" alt="">
                                <img src="../image/comment/empty.png" title="非常滿意" alt="">
                                <span id="score"></span>
                            </div>

                            <p></p>
                            <input type="hidden" asp-for="CommentPoint" value="-1" />
                            <span asp-validation-for="CommentPoint"></span>
                            <br>

                            <div class="sub">
                                <label asp-for="CommentDetail" class="control-label"></label>
                                <textarea asp-for="CommentDetail" cols="40" rows="5" autofocus placeholder="請輸入評論摘要...."></textarea>
                                <span asp-validation-for="CommentDetail" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <input type="submit" value="儲存" class="btn btn-primary" />
                                <input type="reset" value="清除" class="btn btn-secondary" />
                                <a asp-action="ListByAdmin" class="btn btn-warning">取消</a>
                            </div>
                            <div class="form-group">
                                @using (Html.BeginForm("CreateByAdmin", "Comment", new { id = "my-form-id" }))
                                {
                                    <button type="button" class="btn btn-secondary" onclick="demoCommentAdmin()">Demo</button>
                                }
                                @ViewBag.Message
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
@section Scripts {
    <script src="~/js/comment/commentpoint.js"></script>
    <script>
        function demoCommentAdmin() {
            // 設定 Demo 評價
            // 取得表單元素和欄位元素
            document.getElementById("MemberId").value = "MB00006";
            document.getElementById("CommentDetail").value = "給五星不是沒有缺點，但住四個晚上下來整體感受很不錯，下次來台北還是會列為首選。";
            //// 提交表單
            form.submit();
        }
    </script>
    }

HotelOrderFinal/Views/Comment/List.cshtml
@model IEnumerable<HotelOrderFinal.Models.Comment>

@{
    ViewData["Title"] = "List";
}

<section class="breadcrumb_area">
    <div class="overlay bg-parallax" data-stellar-ratio="0.8" data-stellar-vertical-offset="0" data-background=""></div>
    <div class="container">
        <div class="page-cover text-center">
            <h2 class="page-cover-tittle">評論一覽</h2>
        </div>
    </div>
</section>
<head>
    <title>評點&評價</title>
    <style>
        div {
        }

        .card-text {
            -webkit-box-orient: vertical;
            -webkit-line-clamp: 2;
            line-clamp: 2;
            padding: inherit;
            overflow: hidden;
        }

        .card-img {
            display: block;
            margin: 0 auto;
        }

    </style>
</head>
<body>
    <div class="container-fluid">
        <div class="row" style="background-color: #dcebfd;">
            <div class="col-md-2"></div>
            <div class="col-md-10">
                <div class="page-cover text-left">
                    <p>
                        @using (Html.BeginForm())
                        {
                            @:關鍵字 @Html.TextBox("txtKeyword")  <input type="submit"  class="btn btn-light" value="查詢">

                            @using (Html.BeginForm("List", "Comment", new { id = "my-form-id" }))
                            {
                                <button type="button"  class="btn btn-secondary" onclick="demoSearch()">Demo</button>
                            }
                            @ViewBag.Message
                        }
                    </p>
                    <p>
                        <a href="#" class="btn btn-info" data-toggle="modal" data-target="#myAccountModal" data-backdrop="false">請寫下您寶貴的意見</a>
                        @{
                            int count = 0; decimal avgPoint = 0, totPoint = 0;
                            foreach (var item2 in Model)
                            {
                                count++;
                                totPoint += item2.CommentPoint.Value;
                            }
                            if (count > 0) {
                                avgPoint = (totPoint / count);
                            }
                            <span style="color:#2894FF; font-size:1.5em;">　　　評點平均數:@avgPoint.ToString("N2")</span>
                        }
                    </p>
                    <div class="d-flex flex-wrap" style="padding-bottom:10px">
                        @{
                            foreach (var item in Model)
                            {
                                <div class="col-5 col-1-sm-6">
                                    <div class="card" style="width:400px; height:200px;  border-radius:10px;  margin-top:10px; padding-bottom:10px;">

                                        <div class="card-body">
                                            <input type="hidden" value="@Html.DisplayFor(modelItem => item.CommentId)" />
                                            <h5 class="card-title">@Html.DisplayFor(modelItem => item.CommentDate)</h5>
                                            <h5 class="card-title">@Html.DisplayFor(modelItem => item.MemberId)</h5>
                                            <h6 class="card-subtitle mb-2 text-body-secondary">
                                                @for (var i = 0; i < item.CommentPoint; i++)
                                                {
                                                    <img src="../image/comment/shining.png">
                                                }
                                                @Html.DisplayFor(modelItem => item.CommentPoint)
                                                @if (item.CommentClass == 1)
                                                {
                                                    <label style="color:#2894FF">　整體</label>
                                                }
                                                @if (item.CommentClass == 2)
                                                {
                                                    <label style="color:#2894FF">　房間</label>
                                                }
                                                @if (item.CommentClass == 3)
                                                {
                                                    <label style="color:#2894FF">　服務</label>
                                                }
                                            </h6>
                                            <p class="card-text; lnr-highlight:16rem;">@Html.DisplayFor(modelItem => item.CommentDetail)</p>
                                        </div>
                                    </div>
                                </div>
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
@section Scripts
{
    <script src="~/js/comment/demoSearch.js"></script>
}

HotelOrderFinal/Views/Comment/ListByMemberAll.cshtml
@model IEnumerable<HotelOrderFinal.Models.Comment>

@{
    ViewData["Title"] = "ListByMemberAll";
}

<section class="breadcrumb_area">
    <div class="overlay bg-parallax" data-stellar-ratio="0.8" data-stellar-vertical-offset="0" data-background=""></div>
    <div class="container">
        <div class="page-cover text-center">
            <h2 class="page-cover-tittle">會員管理系統:評論一覽</h2>
        </div>
    </div>
</section>
<head>
    <title>評點&評價</title>
    <style>
        div {
        }

        .card-text {
            display: -webkit-box;
            -webkit-box-orient: vertical;
            -webkit-line-clamp: 2;
            line-clamp: 2;
            overflow: hidden;
        }

        .card-img {
            display: block;
            margin: 0 auto;
        }
    </style>
</head>
<body>
    <div class="container-fluid">
        <div class="row" style="background-color: #dcebfd;">
            <div class="col-md-2"></div>
            <div class="col-md-10">
                <div class="page-cover text-left">
                    <p>
                        @using (Html.BeginForm())
                        {
                            @:關鍵字 @Html.TextBox("txtKeyword") <input type="submit" value="查詢">
                            @using (Html.BeginForm("ListbyMemberAll", "Comment", new { id = "my-form-id" }))
                            {
                                <button type="button" class="btn btn-secondary" onclick="demoSearch()">Demo</button>
                            }
                            @ViewBag.Message
                        }
                    </p>
                    <p></p>
                    <p>
                        <a asp-action="Create" class="btn btn-info">請寫下您寶貴的意見</a>
                        @{
                            int count = 0; decimal avgPoint = 0, totPoint = 0;
                            foreach (var item2 in Model)
                            {
                                count++;
                                totPoint += item2.CommentPoint.Value;
                            }
                            if (count > 0)
                            {
                                avgPoint = (totPoint / count);
                            }
                            <span style="color:#2894FF; font-size:1.5em;">　　　評點平均數:@avgPoint.ToString("N2")</span>
                        }

                        <div class="d-flex flex-wrap" style="padding-bottom:10px">
                            @foreach (var item in Model)
                            {
                                <div class="col-5 col-1-sm-6">
                                    <div class="card" style="width:400px; height:200px;  border-radius:10px;  margin-top:10px; padding-bottom:10px;">
                                        <div class="card-body">
                                            <input type="hidden" value="@Html.DisplayFor(modelItem => item.CommentId)" />
                                            <h5 class="card-title">@Html.DisplayFor(modelItem => item.CommentDate)</h5>
                                            <h5 class="card-title">@Html.DisplayFor(modelItem => item.MemberId)</h5>
                                            <h6 class="card-subtitle mb-2 text-body-secondary">
                                                @for (var i = 0; i < item.CommentPoint; i++)
                                                {
                                                    <img src="../image/comment/shining.png">
                                                }
                                                @Html.DisplayFor(modelItem => item.CommentPoint)
                                                @if (item.CommentClass == 1)
                                                {
                                                    <label style="color:#2894FF">　整體</label>
                                                }
                                                @if (item.CommentClass == 2)
                                                {
                                                    <label style="color:#2894FF">　房間</label>
                                                }
                                                @if (item.CommentClass == 3)
                                                {
                                                    <label style="color:#2894FF">　服務</label>
                                                }
                                            </h6>
                                            <p class="card-text; lnr-highlight:16rem;">@Html.DisplayFor(modelItem => item.CommentDetail)</p>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                </div>
            </div>
        </div>
    </div>
</body>
@section Scripts
    {
    <script src="~/js/comment/demoSearch.js"></script>
}