HotelOrderFinal/Models/HotelIndustry.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelOrderFinal.Models
{
    public partial class HotelIndustry
    {
        public HotelIndustry()
        {
            MultipleHotelFacility = new HashSet<MultipleHotelFacility>();
            Room = new HashSet<Room>();
        }

        public int HotelId { get; set; }
        public string HotelName { get; set; }
        public string HotelPhone { get; set; }
        public int? HotelRegionId { get; set; }
        public string HotelAddress { get; set; }
        public string HotelImage { get; set; }
        public string HotelImageDiscription { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }

        public virtual HotelRegionName HotelRegion { get; set; }
        public virtual ICollection<MultipleHotelFacility> MultipleHotelFacility { get; set; }
        public virtual ICollection<Room> Room { get; set; }
    }
}

HotelOrderFinal/Controllers/HotelIndustryController.cs
using HotelOrderFinal.Models;
using HotelOrderFinal.ViewModels;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Plugins;
using System.Text.Json;

namespace HotelOrderFinal.Controllers
{
    public class HotelIndustryController : Controller
    {
        IWebHostEnvironment _enviro;
        public HotelIndustryController(IWebHostEnvironment p)
        {
            _enviro = p;
        }

        public IActionResult ListView()
        {
            HotelOrderContext db = new HotelOrderContext();
            var datas = from c in db.HotelIndustry
                        select c;
            return View(datas);
        }

        public IActionResult List()
        {
            return View();
        }

        public IActionResult Edit(int? id)
        {
            HotelOrderContext db = new HotelOrderContext();
            HotelIndustry Hl = db.HotelIndustry.FirstOrDefault(t => t.HotelId == id);
            if (Hl == null)
                return RedirectToAction("ListView");
            return View(Hl);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CHotelIndustryWrap p)
        {
            HotelOrderContext db = new HotelOrderContext();
            HotelIndustry cust = db.HotelIndustry.FirstOrDefault(t => t.HotelId == p.HotelId);
            if (cust != null)
            {
                if (p.photo != null)
                {
                    string photoName = Guid.NewGuid().ToString() + ".jpg";
                    string path = _enviro.WebRootPath + "/image/" + photoName;
                    p.photo.CopyTo(new FileStream(path, FileMode.Create));
                    cust.HotelImage = photoName;
                }

                cust.HotelName = p.HotelName;
                cust.HotelPhone = p.HotelPhone;
                cust.HotelRegionId = p.HotelRegionId;
                cust.HotelAddress = p.HotelAddress;
                cust.HotelImageDiscription = p.HotelImageDiscription;

                db.SaveChanges();
            }

            return RedirectToAction("ListView");
        }
        public IActionResult Create() //創建資料
        {
            return View();
        }
        [HttpPost]

        public IActionResult Create(HotelIndustry p, CHotelIndustryWrap x)
        {
            HotelOrderContext db = new HotelOrderContext();
            //先創建一個空資料好讓圖片跟內容做導向
            db.HotelIndustry.Add(p);
            db.SaveChanges();
            //
            HotelIndustry cust = db.HotelIndustry.FirstOrDefault(t => t.HotelId == p.HotelId);
            if (x.photo != null)
            {
                string photoName = Guid.NewGuid().ToString() + ".jpg";
                string path = _enviro.WebRootPath + "/image/" + photoName;
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    x.photo.CopyTo(stream);
                }
                cust.HotelImage = photoName;
            }

            cust.HotelName = x.HotelName;
            cust.HotelPhone = x.HotelPhone;
            cust.HotelAddress = x.HotelAddress;
            cust.HotelRegionId = x.HotelRegionId;
            cust.Lat = x.Lat;
            cust.Lng= x.Lng;
            cust.HotelImageDiscription= x.HotelImageDiscription;
            db.SaveChanges();
            return RedirectToAction("ListView");
        }

        //public IActionResult Create(HotelIndustry p)
        //{
        //    HotelOrderContext db = new HotelOrderContext();
        //    db.HotelIndustry.Add(p);
        //    db.SaveChanges();
        //    return RedirectToAction("List");
        //}


        public IActionResult Delete(int? id)
        {
            HotelOrderContext db = new HotelOrderContext();
            HotelIndustry cust = db.HotelIndustry.FirstOrDefault(t => t.HotelId == id);
            if (id != null)
            {
                db.HotelIndustry.Remove(cust);
                db.SaveChanges();
            }
            return RedirectToAction("ListView");
        }
    }
}

HotelOrderFinal/Views/HotelIndustry/Create.cshtml
@model HotelOrderFinal.Models.HotelIndustry

@{
    ViewData["Title"] = "Create";
}
<section class="breadcrumb_area">
    <div class="overlay bg-parallax" data-stellar-ratio="0.8" data-stellar-vertical-offset="0" data-background=""></div>
    <div class="container">
        <div class="page-cover text-center">
            <h2 class="page-cover-tittle">About Us</h2>
            <ol class="breadcrumb">
                <li><a href="index.html">Home</a></li>
                <li class="active">About</li>
            </ol>
        </div>
    </div>
</section>

<div class="row">
    <div class="col-md-6 offset-md-3">
<h1>新增飯店資料</h1>

<h4>飯店資料</h4>
<hr />
<div class="row" >
    <div class="col-md-6">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="HotelName" class="control-label">飯店名稱</label>
                <input asp-for="HotelName" class="form-control" />
                <span asp-validation-for="HotelName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HotelPhone" class="control-label">飯店電話號碼</label>
                <input asp-for="HotelPhone" class="form-control" />
                <span asp-validation-for="HotelPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HotelRegionId" class="control-label">飯店區域ID(北部為1 /中部為2 /南部為3)</label>
                <input asp-for="HotelRegionId" class="form-control" />
                <span asp-validation-for="HotelRegionId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HotelAddress" class="control-label">飯店地址</label>
                <input asp-for="HotelAddress" class="form-control" />
                <span asp-validation-for="HotelAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lat" class="control-label">緯度</label>
                <input asp-for="Lat" class="form-control" />
                <span asp-validation-for="Lat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lng" class="control-label">經度</label>
                <input asp-for="Lng" class="form-control" />
                <span asp-validation-for="Lng" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HotelImageDiscription" class="control-label">飯店內容敘述</label>
                <input asp-for="HotelImageDiscription" class="form-control" />
                <span asp-validation-for="HotelImageDiscription" class="text-danger"></span>
            </div>
            <div class="form-group">
                    <label class="control-label">飯店照片</label>
                    <input type="file" name="photo" class="form-control" />
            </div>

            @*            <div class="form-group col-md-10">
            <label class="control-label">飯店照片</label>
            <input type="file" name="photo" class="form-control" />
            </div>*@
            <br />
            <div class="form-group">
                <input type="submit" value="送出" class="btn btn-primary" style="margin-right:10px; margin-bottom:10px;" />
                <button class="btn btn-secondary" style="margin-right:10px; margin-bottom:10px;" asp-action="ListView">回到飯店一覽</button>
                <button type="button" class="btn btn-secondary" onclick="demo()" style="margin-right:10px; margin-bottom:10px;">Demo</button>
                <br />
                <button class="btn btn-danger" asp-action="Index" asp-controller="Home">回到首頁</button>
            </div>
        </form>
    </div>
</div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        function demo() {
            // 設定 Demo 評價
            // 取得表單元素和欄位元素
            document.getElementById("HotelName").value = "墾丁飯店";
            document.getElementById("HotelPhone").value = "01234567";
            document.getElementById("HotelRegionId").value = 3;
            document.getElementById("HotelAddress").value = "Demo用墾丁飯店住址";
            document.getElementById("Lat").value = 22.05595075828875;
            document.getElementById("Lng").value = 120.77406132125643;
            document.getElementById("HotelImageDiscription").value = "Demo飯店展示用敘述Demo飯店展示用敘述Demo飯店展示用敘述Demo飯店展示用敘述Demo飯店展示用敘述Demo飯店展示用敘述Demo飯店展示用敘述Demo飯店展示用敘述Demo飯店展示用敘述Demo飯店展示用敘述";
        }
    </script>
}

HotelOrderFinal/Views/HotelIndustry/Edit.cshtml
@model HotelOrderFinal.Models.HotelIndustry

@{
    ViewData["Title"] = "Edit";
}
<section class="breadcrumb_area">
    <div class="overlay bg-parallax" data-stellar-ratio="0.8" data-stellar-vertical-offset="0" data-background=""></div>
    <div class="container">
        <div class="page-cover text-center">
            <h2 class="page-cover-tittle">About Us</h2>
            <ol class="breadcrumb">
                <li><a href="index.html">Home</a></li>
                <li class="active">About</li>
            </ol>
        </div>
    </div>
</section>
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h1>飯店業者修改</h1>


<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" value="@Model.HotelId" name="HotelId" />
            <div class="form-group">
                <label asp-for="HotelName" class="control-label">飯店名稱</label>
                <input asp-for="HotelName" class="form-control" />
                <span asp-validation-for="HotelName" class="text-danger"></span>
            </div>
            <div class="form-group">
                        <label asp-for="HotelPhone" class="control-label">飯店電話號碼</label>
                <input asp-for="HotelPhone" class="form-control" />
                <span asp-validation-for="HotelPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HotelRegionId" class="control-label">地區</label>
                <input asp-for="HotelRegionId" class="form-control" />
                <span asp-validation-for="HotelRegionId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HotelAddress" class="control-label">地址</label>
                <input asp-for="HotelAddress" class="form-control" />
                <span asp-validation-for="HotelAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HotelImageDiscription" class="control-label">圖片描述</label>
                <input asp-for="HotelImageDiscription" class="form-control" />
                <span asp-validation-for="HotelImageDiscription" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">飯店照片</label>
                <input type="file" name="photo" class="form-control" />
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="送出" class="btn btn-primary" style="margin-right:10px; margin-bottom:10px;" />
                <button class="btn btn-secondary" style="margin-right:10px; margin-bottom:10px;" asp-action="ListView">回到飯店一覽</button>
                <br />
                <button class="btn btn-danger" style="margin-right:10px; margin-bottom:10px;">@Html.ActionLink("刪除", "Delete", "HotelIndustry", new {id=Model.HotelId}, new { @style="color:white" ,onclick = "return confirm('確定刪除?')"})</button>
                <br />
                <button class="btn btn-secondary" asp-action="Index" asp-controller="Home">回到首頁</button>
            </div>
        </form>
    </div>
</div>
    </div>
</div>
<div>
  @*  <a asp-action="Index">Back to List</a>*@
</div>

@*@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}*@

HotelOrderFinal/Views/HotelIndustry/ListView.cshtml
@model IEnumerable<HotelOrderFinal.Models.HotelIndustry>

@{
    ViewData["Title"] = "ListView";
}
<link rel="stylesheet" href="~/css/ForAdminTable.css">
<style>

    .table td {
        white-space: nowrap; /* 防止内容换行 */
        overflow: hidden; /* 隐藏溢出内容 */
        text-overflow: ellipsis; /* 使用省略号表示溢出内容 */        
        white-space: normal;
    }
</style>

<section class="breadcrumb_area">
    <div class="overlay bg-parallax" data-stellar-ratio="0.8" data-stellar-vertical-offset="0" data-background=""></div>
    <div class="container">
        <div class="page-cover text-center">
            <h2 class="page-cover-tittle">後台管理系統：飯店管理</h2>
        </div>
    </div>
</section>
<div class="Adminwrapper">
    <div class="row">
        <div class="col-xs-12 col-md-2">
            <div class=" ">
                <div class=" ">
                    <div class="">
                        @{
                            var AdminId = Context.Session.GetString("AdminId");
                        }

                    </div>
                </div>
                <div class="">
                    <h2 style="text-align: center">
                        @Html.ActionLink(AdminId, "List", "Admin")
                    </h2>
                    <ul class="list" style="list-style: none; padding: 0;">

                        <!--改成手風琴下拉式-->
                        <li>
                            @Html.ActionLink("會員管理", "List", "MemberMange", null, new { @class = "nav-link Adminbutton  d-flex justify-content-center" })
                        </li>
                        <li>
                            @Html.ActionLink("房型管理", "AdminRoom", "Room", null, new { @class = "nav-link Adminbutton  d-flex justify-content-center" })
                        </li>
                        <li>
                            @Html.ActionLink("活動管理", "ActivityByCreate", "Activity", null, new { @class = "nav-link Adminbutton  d-flex justify-content-center" })
                        </li>
                        <li>
                            @Html.ActionLink("訂房管理", "EditPassword", "Member", null, new { @class = "nav-link Adminbutton  d-flex justify-content-center" })
                        </li>
                        <li>
                            @Html.ActionLink("飯店一覽管理", "ListView", "HotelIndustry", null, new { @class = "nav-link Adminbutton  d-flex justify-content-center" })
                        </li>
                        <li>
                            @Html.ActionLink("優惠折扣管理", "List", "Discount", null, new { @class = "nav-link Adminbutton  d-flex justify-content-center" })
                        </li>
                        <li>
                            @Html.ActionLink("評論管理", "ListByAdmin", "Comment", null, new { @class = "nav-link Adminbutton  d-flex justify-content-center" })
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div id="selectedItemContent" class="col-xs-12 col-md-10 ">
            <!-- 這裡會顯示點選的項目的內容 -->

<table class="table">
    <thead>
        <tr>
            <th>
                飯店名稱
            </th>
            <th>
                飯店電話號碼
            </th>
            <th>
                地址
            </th>
            <th>
                飯店預設圖片
            </th>
            <th>
                圖片描述
            </th>
            <th>
                區域ID<br />(北區為1，中區為2，南區為3)
            </th>
            <th>
                <a asp-action="Create" class="btn btn-primary">新增飯店</a>
            </th>
        </tr>
    </thead>
    <tbody>
            @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.HotelName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HotelPhone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HotelAddress)
            </td>
            <td>
             <img src="~/image/@item.HotelImage" width="160" height="120" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HotelImageDiscription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HotelRegionId)
            </td>
            <td>
                    @Html.ActionLink("修改", "Edit", new {id=item.HotelId},new { @class="btn btn-success" })
                    <br>
                    @Html.ActionLink("刪除", "Delete", new {id=item.HotelId},new { @class="btn btn-danger", onclick="return confirm('確定要刪除嗎?')"})
            </td>
        </tr>
}
    </tbody>
</table>
</div>
</div>
</div>